[package]
name = "rst-mmpbsa"
version = "0.1.0"
edition = "2021"

[dependencies]
rst-core = { path = "../core" }
rayon = "1.11.0"
thiserror = "2"
log = "0.4"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "mmpbsa_bench"
harness = false
